//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article_Info
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article_Info()
        {
            this.Article_Photo = new HashSet<Article_Photo>();
            this.BL_Article = new HashSet<BL_Article>();
            this.Emplacement = new HashSet<Emplacement>();
            this.Article_Reference = new HashSet<Article_Reference>();
        }
    
        public int art_ID { get; set; }
        public string art_Designation { get; set; }
        public string art_Description { get; set; }
        public Nullable<int> svc_ID { get; set; }
        public Nullable<int> fam_ID { get; set; }
        public Nullable<int> unit_M_ID { get; set; }
        public Nullable<bool> art_Status { get; set; }
    
        public virtual Famille Famille { get; set; }
        public virtual Unite_Mesure Unite_Mesure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article_Photo> Article_Photo { get; set; }
        public virtual Service Service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BL_Article> BL_Article { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emplacement> Emplacement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article_Reference> Article_Reference { get; set; }
    }
}
