//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article_CodeBarre
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article_CodeBarre()
        {
            this.BL_Article = new HashSet<BL_Article>();
        }
    
        public int cb_ID { get; set; }
        public Nullable<System.DateTime> cb_Date { get; set; }
        public string cb_Designation { get; set; }
        public Nullable<int> ref_ID { get; set; }
        public Nullable<int> act_ID { get; set; }
        public Nullable<bool> cb_Status { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual Article_Reference Article_Reference { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BL_Article> BL_Article { get; set; }
    }
}
