//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article_Photo
    {
        public int pho_ID { get; set; }
        public string pho_Path { get; set; }
        public string pho_Nom { get; set; }
        public string pho_Extension { get; set; }
        public Nullable<int> art_ID { get; set; }
        public string pho_Description { get; set; }
    
        public virtual Article_Info Article_Info { get; set; }
    }
}
