//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mouvement
    {
        public int mvt_ID { get; set; }
        public Nullable<System.DateTime> mvt_Date { get; set; }
        public string mvt_Doc_Refference { get; set; }
        public Nullable<int> act_ID { get; set; }
        public Nullable<int> unit_M_ID { get; set; }
        public Nullable<int> unit_ID { get; set; }
        public Nullable<int> bl_A_ID { get; set; }
        public string mvt_Obsrvation { get; set; }
    
        public virtual Action Action { get; set; }
        public virtual BL_Article BL_Article { get; set; }
        public virtual Unite_Mesure Unite_Mesure { get; set; }
        public virtual Unite_Type Unite_Type { get; set; }
    }
}
