//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class g_StockEntities : DbContext
    {
        public g_StockEntities()
            : base("name=g_StockEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Action { get; set; }
        public virtual DbSet<Armoire> Armoire { get; set; }
        public virtual DbSet<Article_CodeBarre> Article_CodeBarre { get; set; }
        public virtual DbSet<Article_Info> Article_Info { get; set; }
        public virtual DbSet<Article_Photo> Article_Photo { get; set; }
        public virtual DbSet<Article_Reference> Article_Reference { get; set; }
        public virtual DbSet<BL> BL { get; set; }
        public virtual DbSet<BL_Article> BL_Article { get; set; }
        public virtual DbSet<Emplacement> Emplacement { get; set; }
        public virtual DbSet<Famille> Famille { get; set; }
        public virtual DbSet<Fournisseur> Fournisseur { get; set; }
        public virtual DbSet<Magasin> Magasin { get; set; }
        public virtual DbSet<Mouvement> Mouvement { get; set; }
        public virtual DbSet<Profil> Profil { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<Unite> Unite { get; set; }
        public virtual DbSet<Unite_Mesure> Unite_Mesure { get; set; }
        public virtual DbSet<Unite_Type> Unite_Type { get; set; }
        public virtual DbSet<Utilisateur> Utilisateur { get; set; }
        public virtual DbSet<Rayonnage> Rayonnage { get; set; }
    
        public virtual int Delete_Famille(Nullable<int> fam_ID)
        {
            var fam_IDParameter = fam_ID.HasValue ?
                new ObjectParameter("fam_ID", fam_ID) :
                new ObjectParameter("fam_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Famille", fam_IDParameter);
        }
    
        public virtual int Insert_Famille(Nullable<int> fam_ID, string fam_Nom, string fam_Descripction)
        {
            var fam_IDParameter = fam_ID.HasValue ?
                new ObjectParameter("fam_ID", fam_ID) :
                new ObjectParameter("fam_ID", typeof(int));
    
            var fam_NomParameter = fam_Nom != null ?
                new ObjectParameter("fam_Nom", fam_Nom) :
                new ObjectParameter("fam_Nom", typeof(string));
    
            var fam_DescripctionParameter = fam_Descripction != null ?
                new ObjectParameter("fam_Descripction", fam_Descripction) :
                new ObjectParameter("fam_Descripction", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Famille", fam_IDParameter, fam_NomParameter, fam_DescripctionParameter);
        }
    
        public virtual int Update_Famille(Nullable<int> fam_ID, string fam_Nom, string fam_Descripction)
        {
            var fam_IDParameter = fam_ID.HasValue ?
                new ObjectParameter("fam_ID", fam_ID) :
                new ObjectParameter("fam_ID", typeof(int));
    
            var fam_NomParameter = fam_Nom != null ?
                new ObjectParameter("fam_Nom", fam_Nom) :
                new ObjectParameter("fam_Nom", typeof(string));
    
            var fam_DescripctionParameter = fam_Descripction != null ?
                new ObjectParameter("fam_Descripction", fam_Descripction) :
                new ObjectParameter("fam_Descripction", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Famille", fam_IDParameter, fam_NomParameter, fam_DescripctionParameter);
        }
    
        public virtual ObjectResult<Select_Famille_Result> Select_Famille()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Famille_Result>("Select_Famille");
        }
    
        public virtual ObjectResult<Famille> Select_Famille_By_Famille(string fam_Nom)
        {
            var fam_NomParameter = fam_Nom != null ?
                new ObjectParameter("fam_Nom", fam_Nom) :
                new ObjectParameter("fam_Nom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Famille>("Select_Famille_By_Famille", fam_NomParameter);
        }
    
        public virtual ObjectResult<Famille> Select_Famille_By_Famille(string fam_Nom, MergeOption mergeOption)
        {
            var fam_NomParameter = fam_Nom != null ?
                new ObjectParameter("fam_Nom", fam_Nom) :
                new ObjectParameter("fam_Nom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Famille>("Select_Famille_By_Famille", mergeOption, fam_NomParameter);
        }
    
        public virtual ObjectResult<Famille> Select_Famille_By_ID(Nullable<int> fam_ID)
        {
            var fam_IDParameter = fam_ID.HasValue ?
                new ObjectParameter("fam_ID", fam_ID) :
                new ObjectParameter("fam_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Famille>("Select_Famille_By_ID", fam_IDParameter);
        }
    
        public virtual ObjectResult<Famille> Select_Famille_By_ID(Nullable<int> fam_ID, MergeOption mergeOption)
        {
            var fam_IDParameter = fam_ID.HasValue ?
                new ObjectParameter("fam_ID", fam_ID) :
                new ObjectParameter("fam_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Famille>("Select_Famille_By_ID", mergeOption, fam_IDParameter);
        }
    
        public virtual int Delete_Service(Nullable<int> svc_ID)
        {
            var svc_IDParameter = svc_ID.HasValue ?
                new ObjectParameter("svc_ID", svc_ID) :
                new ObjectParameter("svc_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Service", svc_IDParameter);
        }
    
        public virtual int Insert_Service(Nullable<int> svc_ID, string svc_Nom, string svc_description, Nullable<System.DateTime> svc_Date)
        {
            var svc_IDParameter = svc_ID.HasValue ?
                new ObjectParameter("svc_ID", svc_ID) :
                new ObjectParameter("svc_ID", typeof(int));
    
            var svc_NomParameter = svc_Nom != null ?
                new ObjectParameter("svc_Nom", svc_Nom) :
                new ObjectParameter("svc_Nom", typeof(string));
    
            var svc_descriptionParameter = svc_description != null ?
                new ObjectParameter("svc_description", svc_description) :
                new ObjectParameter("svc_description", typeof(string));
    
            var svc_DateParameter = svc_Date.HasValue ?
                new ObjectParameter("svc_Date", svc_Date) :
                new ObjectParameter("svc_Date", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Service", svc_IDParameter, svc_NomParameter, svc_descriptionParameter, svc_DateParameter);
        }
    
        public virtual ObjectResult<Select_Service_Result> Select_Service()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Service_Result>("Select_Service");
        }
    
        public virtual ObjectResult<Service> Select_Service_By_ID(Nullable<int> svc_ID)
        {
            var svc_IDParameter = svc_ID.HasValue ?
                new ObjectParameter("svc_ID", svc_ID) :
                new ObjectParameter("svc_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Service>("Select_Service_By_ID", svc_IDParameter);
        }
    
        public virtual ObjectResult<Service> Select_Service_By_ID(Nullable<int> svc_ID, MergeOption mergeOption)
        {
            var svc_IDParameter = svc_ID.HasValue ?
                new ObjectParameter("svc_ID", svc_ID) :
                new ObjectParameter("svc_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Service>("Select_Service_By_ID", mergeOption, svc_IDParameter);
        }
    
        public virtual ObjectResult<Service> Select_Service_By_Service(string svc_Nom)
        {
            var svc_NomParameter = svc_Nom != null ?
                new ObjectParameter("svc_Nom", svc_Nom) :
                new ObjectParameter("svc_Nom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Service>("Select_Service_By_Service", svc_NomParameter);
        }
    
        public virtual ObjectResult<Service> Select_Service_By_Service(string svc_Nom, MergeOption mergeOption)
        {
            var svc_NomParameter = svc_Nom != null ?
                new ObjectParameter("svc_Nom", svc_Nom) :
                new ObjectParameter("svc_Nom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Service>("Select_Service_By_Service", mergeOption, svc_NomParameter);
        }
    
        public virtual int Update_Service(Nullable<int> svc_ID, string svc_Nom, string svc_description)
        {
            var svc_IDParameter = svc_ID.HasValue ?
                new ObjectParameter("svc_ID", svc_ID) :
                new ObjectParameter("svc_ID", typeof(int));
    
            var svc_NomParameter = svc_Nom != null ?
                new ObjectParameter("svc_Nom", svc_Nom) :
                new ObjectParameter("svc_Nom", typeof(string));
    
            var svc_descriptionParameter = svc_description != null ?
                new ObjectParameter("svc_description", svc_description) :
                new ObjectParameter("svc_description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Service", svc_IDParameter, svc_NomParameter, svc_descriptionParameter);
        }
    
        public virtual int Delete_Profil(Nullable<int> prof_ID)
        {
            var prof_IDParameter = prof_ID.HasValue ?
                new ObjectParameter("prof_ID", prof_ID) :
                new ObjectParameter("prof_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Profil", prof_IDParameter);
        }
    
        public virtual int Insert_Profil(Nullable<int> prof_ID, string prof_Nom, string prof_Description)
        {
            var prof_IDParameter = prof_ID.HasValue ?
                new ObjectParameter("prof_ID", prof_ID) :
                new ObjectParameter("prof_ID", typeof(int));
    
            var prof_NomParameter = prof_Nom != null ?
                new ObjectParameter("prof_Nom", prof_Nom) :
                new ObjectParameter("prof_Nom", typeof(string));
    
            var prof_DescriptionParameter = prof_Description != null ?
                new ObjectParameter("prof_Description", prof_Description) :
                new ObjectParameter("prof_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Profil", prof_IDParameter, prof_NomParameter, prof_DescriptionParameter);
        }
    
        public virtual ObjectResult<Select_Profil_Result> Select_Profil()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Profil_Result>("Select_Profil");
        }
    
        public virtual ObjectResult<Profil> Select_Profil_By_ID(Nullable<int> prof_ID)
        {
            var prof_IDParameter = prof_ID.HasValue ?
                new ObjectParameter("prof_ID", prof_ID) :
                new ObjectParameter("prof_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Profil>("Select_Profil_By_ID", prof_IDParameter);
        }
    
        public virtual ObjectResult<Profil> Select_Profil_By_ID(Nullable<int> prof_ID, MergeOption mergeOption)
        {
            var prof_IDParameter = prof_ID.HasValue ?
                new ObjectParameter("prof_ID", prof_ID) :
                new ObjectParameter("prof_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Profil>("Select_Profil_By_ID", mergeOption, prof_IDParameter);
        }
    
        public virtual ObjectResult<Profil> Select_Profil_By_Profil(string prof_Nom)
        {
            var prof_NomParameter = prof_Nom != null ?
                new ObjectParameter("prof_Nom", prof_Nom) :
                new ObjectParameter("prof_Nom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Profil>("Select_Profil_By_Profil", prof_NomParameter);
        }
    
        public virtual ObjectResult<Profil> Select_Profil_By_Profil(string prof_Nom, MergeOption mergeOption)
        {
            var prof_NomParameter = prof_Nom != null ?
                new ObjectParameter("prof_Nom", prof_Nom) :
                new ObjectParameter("prof_Nom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Profil>("Select_Profil_By_Profil", mergeOption, prof_NomParameter);
        }
    
        public virtual int Update_Profil(Nullable<int> prof_ID, string prof_Nom, string prof_Description)
        {
            var prof_IDParameter = prof_ID.HasValue ?
                new ObjectParameter("prof_ID", prof_ID) :
                new ObjectParameter("prof_ID", typeof(int));
    
            var prof_NomParameter = prof_Nom != null ?
                new ObjectParameter("prof_Nom", prof_Nom) :
                new ObjectParameter("prof_Nom", typeof(string));
    
            var prof_DescriptionParameter = prof_Description != null ?
                new ObjectParameter("prof_Description", prof_Description) :
                new ObjectParameter("prof_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Profil", prof_IDParameter, prof_NomParameter, prof_DescriptionParameter);
        }
    
        public virtual ObjectResult<select_vw_Utilisateur_Result> select_vw_Utilisateur()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<select_vw_Utilisateur_Result>("select_vw_Utilisateur");
        }
    
        public virtual int Delete_Utilisateur(Nullable<int> util_ID)
        {
            var util_IDParameter = util_ID.HasValue ?
                new ObjectParameter("util_ID", util_ID) :
                new ObjectParameter("util_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Utilisateur", util_IDParameter);
        }
    
        public virtual int Insert_Utilisateur(Nullable<int> util_ID, string util_Nom, Nullable<System.DateTime> util_Date, string util_Identifiant, string util_MotPasse, Nullable<int> svc_ID, Nullable<int> prof_ID)
        {
            var util_IDParameter = util_ID.HasValue ?
                new ObjectParameter("util_ID", util_ID) :
                new ObjectParameter("util_ID", typeof(int));
    
            var util_NomParameter = util_Nom != null ?
                new ObjectParameter("util_Nom", util_Nom) :
                new ObjectParameter("util_Nom", typeof(string));
    
            var util_DateParameter = util_Date.HasValue ?
                new ObjectParameter("util_Date", util_Date) :
                new ObjectParameter("util_Date", typeof(System.DateTime));
    
            var util_IdentifiantParameter = util_Identifiant != null ?
                new ObjectParameter("util_Identifiant", util_Identifiant) :
                new ObjectParameter("util_Identifiant", typeof(string));
    
            var util_MotPasseParameter = util_MotPasse != null ?
                new ObjectParameter("util_MotPasse", util_MotPasse) :
                new ObjectParameter("util_MotPasse", typeof(string));
    
            var svc_IDParameter = svc_ID.HasValue ?
                new ObjectParameter("svc_ID", svc_ID) :
                new ObjectParameter("svc_ID", typeof(int));
    
            var prof_IDParameter = prof_ID.HasValue ?
                new ObjectParameter("prof_ID", prof_ID) :
                new ObjectParameter("prof_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Utilisateur", util_IDParameter, util_NomParameter, util_DateParameter, util_IdentifiantParameter, util_MotPasseParameter, svc_IDParameter, prof_IDParameter);
        }
    
        public virtual ObjectResult<Utilisateur> Select_Utilisateur_By_ID(Nullable<int> util_ID)
        {
            var util_IDParameter = util_ID.HasValue ?
                new ObjectParameter("util_ID", util_ID) :
                new ObjectParameter("util_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Utilisateur>("Select_Utilisateur_By_ID", util_IDParameter);
        }
    
        public virtual ObjectResult<Utilisateur> Select_Utilisateur_By_ID(Nullable<int> util_ID, MergeOption mergeOption)
        {
            var util_IDParameter = util_ID.HasValue ?
                new ObjectParameter("util_ID", util_ID) :
                new ObjectParameter("util_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Utilisateur>("Select_Utilisateur_By_ID", mergeOption, util_IDParameter);
        }
    
        public virtual ObjectResult<Utilisateur> Select_Utilisateur_By_User(string util_Identifiant)
        {
            var util_IdentifiantParameter = util_Identifiant != null ?
                new ObjectParameter("util_Identifiant", util_Identifiant) :
                new ObjectParameter("util_Identifiant", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Utilisateur>("Select_Utilisateur_By_User", util_IdentifiantParameter);
        }
    
        public virtual ObjectResult<Utilisateur> Select_Utilisateur_By_User(string util_Identifiant, MergeOption mergeOption)
        {
            var util_IdentifiantParameter = util_Identifiant != null ?
                new ObjectParameter("util_Identifiant", util_Identifiant) :
                new ObjectParameter("util_Identifiant", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Utilisateur>("Select_Utilisateur_By_User", mergeOption, util_IdentifiantParameter);
        }
    
        public virtual int Update_Utilisateur(Nullable<int> util_ID, string util_Nom, string util_Identifiant, string util_MotPasse, Nullable<int> svc_ID, Nullable<int> prof_ID)
        {
            var util_IDParameter = util_ID.HasValue ?
                new ObjectParameter("util_ID", util_ID) :
                new ObjectParameter("util_ID", typeof(int));
    
            var util_NomParameter = util_Nom != null ?
                new ObjectParameter("util_Nom", util_Nom) :
                new ObjectParameter("util_Nom", typeof(string));
    
            var util_IdentifiantParameter = util_Identifiant != null ?
                new ObjectParameter("util_Identifiant", util_Identifiant) :
                new ObjectParameter("util_Identifiant", typeof(string));
    
            var util_MotPasseParameter = util_MotPasse != null ?
                new ObjectParameter("util_MotPasse", util_MotPasse) :
                new ObjectParameter("util_MotPasse", typeof(string));
    
            var svc_IDParameter = svc_ID.HasValue ?
                new ObjectParameter("svc_ID", svc_ID) :
                new ObjectParameter("svc_ID", typeof(int));
    
            var prof_IDParameter = prof_ID.HasValue ?
                new ObjectParameter("prof_ID", prof_ID) :
                new ObjectParameter("prof_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Utilisateur", util_IDParameter, util_NomParameter, util_IdentifiantParameter, util_MotPasseParameter, svc_IDParameter, prof_IDParameter);
        }
    
        public virtual ObjectResult<Search_Utilisateur_Result> Search_Utilisateur(string mode, string search, Nullable<System.DateTime> dt1, Nullable<System.DateTime> dt2)
        {
            var modeParameter = mode != null ?
                new ObjectParameter("mode", mode) :
                new ObjectParameter("mode", typeof(string));
    
            var searchParameter = search != null ?
                new ObjectParameter("Search", search) :
                new ObjectParameter("Search", typeof(string));
    
            var dt1Parameter = dt1.HasValue ?
                new ObjectParameter("dt1", dt1) :
                new ObjectParameter("dt1", typeof(System.DateTime));
    
            var dt2Parameter = dt2.HasValue ?
                new ObjectParameter("dt2", dt2) :
                new ObjectParameter("dt2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Search_Utilisateur_Result>("Search_Utilisateur", modeParameter, searchParameter, dt1Parameter, dt2Parameter);
        }
    
        public virtual ObjectResult<Select_Service_By_Nom_Result> Select_Service_By_Nom()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Service_By_Nom_Result>("Select_Service_By_Nom");
        }
    
        public virtual int Delete_Magasin(Nullable<int> mags_ID)
        {
            var mags_IDParameter = mags_ID.HasValue ?
                new ObjectParameter("mags_ID", mags_ID) :
                new ObjectParameter("mags_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Magasin", mags_IDParameter);
        }
    
        public virtual int Insert_Magasin(Nullable<int> mags_ID, string mags_Magasin, string mags_Ville, string mags_Description)
        {
            var mags_IDParameter = mags_ID.HasValue ?
                new ObjectParameter("mags_ID", mags_ID) :
                new ObjectParameter("mags_ID", typeof(int));
    
            var mags_MagasinParameter = mags_Magasin != null ?
                new ObjectParameter("mags_Magasin", mags_Magasin) :
                new ObjectParameter("mags_Magasin", typeof(string));
    
            var mags_VilleParameter = mags_Ville != null ?
                new ObjectParameter("mags_Ville", mags_Ville) :
                new ObjectParameter("mags_Ville", typeof(string));
    
            var mags_DescriptionParameter = mags_Description != null ?
                new ObjectParameter("mags_Description", mags_Description) :
                new ObjectParameter("mags_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Magasin", mags_IDParameter, mags_MagasinParameter, mags_VilleParameter, mags_DescriptionParameter);
        }
    
        public virtual ObjectResult<Select_Magasin_Result> Select_Magasin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Magasin_Result>("Select_Magasin");
        }
    
        public virtual int Update_Magasin(Nullable<int> mags_ID, string mags_Magasin, string mags_Ville, string mags_Description)
        {
            var mags_IDParameter = mags_ID.HasValue ?
                new ObjectParameter("mags_ID", mags_ID) :
                new ObjectParameter("mags_ID", typeof(int));
    
            var mags_MagasinParameter = mags_Magasin != null ?
                new ObjectParameter("mags_Magasin", mags_Magasin) :
                new ObjectParameter("mags_Magasin", typeof(string));
    
            var mags_VilleParameter = mags_Ville != null ?
                new ObjectParameter("mags_Ville", mags_Ville) :
                new ObjectParameter("mags_Ville", typeof(string));
    
            var mags_DescriptionParameter = mags_Description != null ?
                new ObjectParameter("mags_Description", mags_Description) :
                new ObjectParameter("mags_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Magasin", mags_IDParameter, mags_MagasinParameter, mags_VilleParameter, mags_DescriptionParameter);
        }
    
        public virtual ObjectResult<Magasin> Select_Magasin_By_ID(Nullable<int> mags_ID)
        {
            var mags_IDParameter = mags_ID.HasValue ?
                new ObjectParameter("mags_ID", mags_ID) :
                new ObjectParameter("mags_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Magasin>("Select_Magasin_By_ID", mags_IDParameter);
        }
    
        public virtual ObjectResult<Magasin> Select_Magasin_By_ID(Nullable<int> mags_ID, MergeOption mergeOption)
        {
            var mags_IDParameter = mags_ID.HasValue ?
                new ObjectParameter("mags_ID", mags_ID) :
                new ObjectParameter("mags_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Magasin>("Select_Magasin_By_ID", mergeOption, mags_IDParameter);
        }
    
        public virtual ObjectResult<Select_Armoire_Result> Select_Armoire(Nullable<int> rayo_ID)
        {
            var rayo_IDParameter = rayo_ID.HasValue ?
                new ObjectParameter("rayo_ID", rayo_ID) :
                new ObjectParameter("rayo_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Armoire_Result>("Select_Armoire", rayo_IDParameter);
        }
    
        public virtual int Delete_Armoire(Nullable<int> arm_ID)
        {
            var arm_IDParameter = arm_ID.HasValue ?
                new ObjectParameter("arm_ID", arm_ID) :
                new ObjectParameter("arm_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Armoire", arm_IDParameter);
        }
    
        public virtual int Delete_Rayonnage(Nullable<int> rayo_ID)
        {
            var rayo_IDParameter = rayo_ID.HasValue ?
                new ObjectParameter("rayo_ID", rayo_ID) :
                new ObjectParameter("rayo_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Delete_Rayonnage", rayo_IDParameter);
        }
    
        public virtual int Insert_Armoire(Nullable<int> arm_ID, string arm_Nom, string arm_Description, Nullable<int> rayo_ID)
        {
            var arm_IDParameter = arm_ID.HasValue ?
                new ObjectParameter("arm_ID", arm_ID) :
                new ObjectParameter("arm_ID", typeof(int));
    
            var arm_NomParameter = arm_Nom != null ?
                new ObjectParameter("arm_Nom", arm_Nom) :
                new ObjectParameter("arm_Nom", typeof(string));
    
            var arm_DescriptionParameter = arm_Description != null ?
                new ObjectParameter("arm_Description", arm_Description) :
                new ObjectParameter("arm_Description", typeof(string));
    
            var rayo_IDParameter = rayo_ID.HasValue ?
                new ObjectParameter("rayo_ID", rayo_ID) :
                new ObjectParameter("rayo_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Armoire", arm_IDParameter, arm_NomParameter, arm_DescriptionParameter, rayo_IDParameter);
        }
    
        public virtual int Insert_Rayonnage(Nullable<int> rayo_ID, string rayo_Nom, string rayo_Description)
        {
            var rayo_IDParameter = rayo_ID.HasValue ?
                new ObjectParameter("rayo_ID", rayo_ID) :
                new ObjectParameter("rayo_ID", typeof(int));
    
            var rayo_NomParameter = rayo_Nom != null ?
                new ObjectParameter("rayo_Nom", rayo_Nom) :
                new ObjectParameter("rayo_Nom", typeof(string));
    
            var rayo_DescriptionParameter = rayo_Description != null ?
                new ObjectParameter("rayo_Description", rayo_Description) :
                new ObjectParameter("rayo_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Rayonnage", rayo_IDParameter, rayo_NomParameter, rayo_DescriptionParameter);
        }
    
        public virtual ObjectResult<Select_Armoire_By_Rayonage_Result> Select_Armoire_By_Rayonage(Nullable<int> rayo_ID)
        {
            var rayo_IDParameter = rayo_ID.HasValue ?
                new ObjectParameter("rayo_ID", rayo_ID) :
                new ObjectParameter("rayo_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Armoire_By_Rayonage_Result>("Select_Armoire_By_Rayonage", rayo_IDParameter);
        }
    
        public virtual ObjectResult<Select_Rayonnage_Result> Select_Rayonnage()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Select_Rayonnage_Result>("Select_Rayonnage");
        }
    
        public virtual ObjectResult<Rayonnage> Select_Rayonnage_By_ID(Nullable<int> rayo_ID)
        {
            var rayo_IDParameter = rayo_ID.HasValue ?
                new ObjectParameter("rayo_ID", rayo_ID) :
                new ObjectParameter("rayo_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rayonnage>("Select_Rayonnage_By_ID", rayo_IDParameter);
        }
    
        public virtual ObjectResult<Rayonnage> Select_Rayonnage_By_ID(Nullable<int> rayo_ID, MergeOption mergeOption)
        {
            var rayo_IDParameter = rayo_ID.HasValue ?
                new ObjectParameter("rayo_ID", rayo_ID) :
                new ObjectParameter("rayo_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rayonnage>("Select_Rayonnage_By_ID", mergeOption, rayo_IDParameter);
        }
    
        public virtual int Update_Armoire(Nullable<int> arm_ID, string arm_Nom, string arm_Description)
        {
            var arm_IDParameter = arm_ID.HasValue ?
                new ObjectParameter("arm_ID", arm_ID) :
                new ObjectParameter("arm_ID", typeof(int));
    
            var arm_NomParameter = arm_Nom != null ?
                new ObjectParameter("arm_Nom", arm_Nom) :
                new ObjectParameter("arm_Nom", typeof(string));
    
            var arm_DescriptionParameter = arm_Description != null ?
                new ObjectParameter("arm_Description", arm_Description) :
                new ObjectParameter("arm_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Armoire", arm_IDParameter, arm_NomParameter, arm_DescriptionParameter);
        }
    
        public virtual int Update_Rayonnage(Nullable<int> rayo_ID, string rayo_Nom, string rayo_Description)
        {
            var rayo_IDParameter = rayo_ID.HasValue ?
                new ObjectParameter("rayo_ID", rayo_ID) :
                new ObjectParameter("rayo_ID", typeof(int));
    
            var rayo_NomParameter = rayo_Nom != null ?
                new ObjectParameter("rayo_Nom", rayo_Nom) :
                new ObjectParameter("rayo_Nom", typeof(string));
    
            var rayo_DescriptionParameter = rayo_Description != null ?
                new ObjectParameter("rayo_Description", rayo_Description) :
                new ObjectParameter("rayo_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_Rayonnage", rayo_IDParameter, rayo_NomParameter, rayo_DescriptionParameter);
        }
    
        public virtual ObjectResult<Rayonnage> Select_Rayonnage_By_Nom(string rayo_Nom)
        {
            var rayo_NomParameter = rayo_Nom != null ?
                new ObjectParameter("rayo_Nom", rayo_Nom) :
                new ObjectParameter("rayo_Nom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rayonnage>("Select_Rayonnage_By_Nom", rayo_NomParameter);
        }
    
        public virtual ObjectResult<Rayonnage> Select_Rayonnage_By_Nom(string rayo_Nom, MergeOption mergeOption)
        {
            var rayo_NomParameter = rayo_Nom != null ?
                new ObjectParameter("rayo_Nom", rayo_Nom) :
                new ObjectParameter("rayo_Nom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Rayonnage>("Select_Rayonnage_By_Nom", mergeOption, rayo_NomParameter);
        }
    
        public virtual int Insert_Armoire_By_Rayonnage(Nullable<int> arm_ID, string arm_Nom, string arm_Description, string rayo_Nom)
        {
            var arm_IDParameter = arm_ID.HasValue ?
                new ObjectParameter("arm_ID", arm_ID) :
                new ObjectParameter("arm_ID", typeof(int));
    
            var arm_NomParameter = arm_Nom != null ?
                new ObjectParameter("arm_Nom", arm_Nom) :
                new ObjectParameter("arm_Nom", typeof(string));
    
            var arm_DescriptionParameter = arm_Description != null ?
                new ObjectParameter("arm_Description", arm_Description) :
                new ObjectParameter("arm_Description", typeof(string));
    
            var rayo_NomParameter = rayo_Nom != null ?
                new ObjectParameter("rayo_Nom", rayo_Nom) :
                new ObjectParameter("rayo_Nom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_Armoire_By_Rayonnage", arm_IDParameter, arm_NomParameter, arm_DescriptionParameter, rayo_NomParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Armoire()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Armoire");
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Article_CodeBarre()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Article_CodeBarre");
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Article_Info()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Article_Info");
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Article_Photo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Article_Photo");
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Article_Reference()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Article_Reference");
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_BL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_BL");
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_BL_Article()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_BL_Article");
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Emplacement()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Emplacement");
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Famille()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Famille");
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Fournisseur()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Fournisseur");
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Magasin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Magasin");
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Mouvement()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Mouvement");
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Profil()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Profil");
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Rayonnage()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Rayonnage");
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Service()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Service");
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Unite()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Unite");
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Unite_Mesure()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Unite_Mesure");
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Unite_Type()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Unite_Type");
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Utilisateur()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Utilisateur");
        }
    
        public virtual ObjectResult<Nullable<int>> MaxID_Action()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("MaxID_Action");
        }
    
        public virtual ObjectResult<Armoire> Select_Armoire_By_ID(Nullable<int> arm_ID)
        {
            var arm_IDParameter = arm_ID.HasValue ?
                new ObjectParameter("arm_ID", arm_ID) :
                new ObjectParameter("arm_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Armoire>("Select_Armoire_By_ID", arm_IDParameter);
        }
    
        public virtual ObjectResult<Armoire> Select_Armoire_By_ID(Nullable<int> arm_ID, MergeOption mergeOption)
        {
            var arm_IDParameter = arm_ID.HasValue ?
                new ObjectParameter("arm_ID", arm_ID) :
                new ObjectParameter("arm_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Armoire>("Select_Armoire_By_ID", mergeOption, arm_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Count_vw_rayonnage(Nullable<int> rayo_ID)
        {
            var rayo_IDParameter = rayo_ID.HasValue ?
                new ObjectParameter("rayo_ID", rayo_ID) :
                new ObjectParameter("rayo_ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Count_vw_rayonnage", rayo_IDParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Count_Rayonnage_By_Nom(string rayo_Nom)
        {
            var rayo_NomParameter = rayo_Nom != null ?
                new ObjectParameter("rayo_Nom", rayo_Nom) :
                new ObjectParameter("rayo_Nom", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Count_Rayonnage_By_Nom", rayo_NomParameter);
        }
    }
}
